services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/temp:/app/temp
    restart: always
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    command: streamlit run streamlit_app/app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    restart: always
    env_file:
      - .env
