services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - WANDB_API_KEY=${WANDB_API_KEY}
    volumes:
      - ./backend/temp:/app/temp
    depends_on:
      - mlflow
    restart: always

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    command: streamlit run streamlit_app/main.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_URL=${API_URL}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
      - WANDB_API_KEY=${WANDB_API_KEY}
    env_file:
      - .env
    depends_on:
      - backend
    restart: always

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_BACKEND_STORE_URI=/mlruns
      - MLFLOW_ARTIFACT_ROOT=/mlruns
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlruns --default-artifact-root /mlruns
    restart: always
